import { Arimo } from "next/font/google";
import "./globals.css";
import Context from "./Context/Context";


const arimo = Arimo({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={arimo.className} >
        <Context>

          {children}
        </Context>
      </body>
    </html>
  );
}
